// Code generated by MockGen. DO NOT EDIT.
// Source: client.go

// Package booker is a generated GoMock package.
package booker

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockClientInterface is a mock of ClientInterface interface.
type MockClientInterface struct {
	ctrl     *gomock.Controller
	recorder *MockClientInterfaceMockRecorder
}

// MockClientInterfaceMockRecorder is the mock recorder for MockClientInterface.
type MockClientInterfaceMockRecorder struct {
	mock *MockClientInterface
}

// NewMockClientInterface creates a new mock instance.
func NewMockClientInterface(ctrl *gomock.Controller) *MockClientInterface {
	mock := &MockClientInterface{ctrl: ctrl}
	mock.recorder = &MockClientInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClientInterface) EXPECT() *MockClientInterfaceMockRecorder {
	return m.recorder
}

// BookTeeTime mocks base method.
func (m *MockClientInterface) BookTeeTime(token string, input GolfNewBooking2Input, debug bool) (*BookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BookTeeTime", token, input, debug)
	ret0, _ := ret[0].(*BookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BookTeeTime indicates an expected call of BookTeeTime.
func (mr *MockClientInterfaceMockRecorder) BookTeeTime(token, input, debug interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BookTeeTime", reflect.TypeOf((*MockClientInterface)(nil).BookTeeTime), token, input, debug)
}

// CancelBooking mocks base method.
func (m *MockClientInterface) CancelBooking(token, accountID, bookingID string) (*GolfCancelBookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelBooking", token, accountID, bookingID)
	ret0, _ := ret[0].(*GolfCancelBookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelBooking indicates an expected call of CancelBooking.
func (mr *MockClientInterfaceMockRecorder) CancelBooking(token, accountID, bookingID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelBooking", reflect.TypeOf((*MockClientInterface)(nil).CancelBooking), token, accountID, bookingID)
}

// CheckTeeTimeStatus mocks base method.
func (m *MockClientInterface) CheckTeeTimeStatus(token string, input GolfCheckTeeTimeStatusInput) (*CheckTeeTimeStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckTeeTimeStatus", token, input)
	ret0, _ := ret[0].(*CheckTeeTimeStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckTeeTimeStatus indicates an expected call of CheckTeeTimeStatus.
func (mr *MockClientInterfaceMockRecorder) CheckTeeTimeStatus(token, input interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckTeeTimeStatus", reflect.TypeOf((*MockClientInterface)(nil).CheckTeeTimeStatus), token, input)
}

// GetBooking mocks base method.
func (m *MockClientInterface) GetBooking(token, accountID, bookingID, chitID string) (*GetBookingResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBooking", token, accountID, bookingID, chitID)
	ret0, _ := ret[0].(*GetBookingResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBooking indicates an expected call of GetBooking.
func (mr *MockClientInterfaceMockRecorder) GetBooking(token, accountID, bookingID, chitID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBooking", reflect.TypeOf((*MockClientInterface)(nil).GetBooking), token, accountID, bookingID, chitID)
}

// GetTeeTimeSlots mocks base method.
func (m *MockClientInterface) GetTeeTimeSlots(token, courseID, txnDate string) ([]TeeTimeSlot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeeTimeSlots", token, courseID, txnDate)
	ret0, _ := ret[0].([]TeeTimeSlot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeeTimeSlots indicates an expected call of GetTeeTimeSlots.
func (mr *MockClientInterfaceMockRecorder) GetTeeTimeSlots(token, courseID, txnDate interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeeTimeSlots", reflect.TypeOf((*MockClientInterface)(nil).GetTeeTimeSlots), token, courseID, txnDate)
}

// Login mocks base method.
func (m *MockClientInterface) Login(userName, password string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Login", userName, password)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Login indicates an expected call of Login.
func (mr *MockClientInterfaceMockRecorder) Login(userName, password interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Login", reflect.TypeOf((*MockClientInterface)(nil).Login), userName, password)
}
