run:
  timeout: 5m

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - unused
    - gofmt
    - ineffassign
    - typecheck

issues:
  exclude-use-default: false
  max-issues-per-linter: 50
  max-same-issues: 3
