services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: forecast
      POSTGRES_USER: forecast
      POSTGRES_PASSWORD: forecast
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
