// Code generated by MockGen. DO NOT EDIT.
// Source: history.go

// Package history is a generated GoMock package.
package history

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetAttempts mocks base method.
func (m *MockService) GetAttempts(userName string, limit int) ([]Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttempts", userName, limit)
	ret0, _ := ret[0].([]Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttempts indicates an expected call of GetAttempts.
func (mr *MockServiceMockRecorder) GetAttempts(userName, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttempts", reflect.TypeOf((*MockService)(nil).GetAttempts), userName, limit)
}

// LogAttempt mocks base method.
func (m *MockService) LogAttempt(a Attempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAttempt", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAttempt indicates an expected call of LogAttempt.
func (mr *MockServiceMockRecorder) LogAttempt(a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAttempt", reflect.TypeOf((*MockService)(nil).LogAttempt), a)
}

// PruneAttempts mocks base method.
func (m *MockService) PruneAttempts(retention time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneAttempts", retention)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PruneAttempts indicates an expected call of PruneAttempts.
func (mr *MockServiceMockRecorder) PruneAttempts(retention interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneAttempts", reflect.TypeOf((*MockService)(nil).PruneAttempts), retention)
}
