// Code generated by MockGen. DO NOT EDIT.
// Source: preset.go

// Package preset is a generated GoMock package.
package preset

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface.
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService.
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance.
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// ClearCancelRequested mocks base method.
func (m *MockService) ClearCancelRequested(userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCancelRequested", userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCancelRequested indicates an expected call of ClearCancelRequested.
func (mr *MockServiceMockRecorder) ClearCancelRequested(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCancelRequested", reflect.TypeOf((*MockService)(nil).ClearCancelRequested), userName)
}

// ClearCourseOverride mocks base method.
func (m *MockService) ClearCourseOverride(userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearCourseOverride", userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearCourseOverride indicates an expected call of ClearCourseOverride.
func (mr *MockServiceMockRecorder) ClearCourseOverride(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearCourseOverride", reflect.TypeOf((*MockService)(nil).ClearCourseOverride), userName)
}

// ClearSkipNextRun mocks base method.
func (m *MockService) ClearSkipNextRun(userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearSkipNextRun", userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// ClearSkipNextRun indicates an expected call of ClearSkipNextRun.
func (mr *MockServiceMockRecorder) ClearSkipNextRun(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearSkipNextRun", reflect.TypeOf((*MockService)(nil).ClearSkipNextRun), userName)
}

// ConsumeSkipNextRun mocks base method.
func (m *MockService) ConsumeSkipNextRun(userName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConsumeSkipNextRun", userName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConsumeSkipNextRun indicates an expected call of ConsumeSkipNextRun.
func (mr *MockServiceMockRecorder) ConsumeSkipNextRun(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConsumeSkipNextRun", reflect.TypeOf((*MockService)(nil).ConsumeSkipNextRun), userName)
}

// DeleteByUserName mocks base method.
func (m *MockService) DeleteByUserName(userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserName", userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserName indicates an expected call of DeleteByUserName.
func (mr *MockServiceMockRecorder) DeleteByUserName(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserName", reflect.TypeOf((*MockService)(nil).DeleteByUserName), userName)
}

// GetEnabledPresets mocks base method.
func (m *MockService) GetEnabledPresets() ([]Preset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledPresets")
	ret0, _ := ret[0].([]Preset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledPresets indicates an expected call of GetEnabledPresets.
func (mr *MockServiceMockRecorder) GetEnabledPresets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledPresets", reflect.TypeOf((*MockService)(nil).GetEnabledPresets))
}

// GetPreset mocks base method.
func (m *MockService) GetPreset(userName string) (*Preset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreset", userName)
	ret0, _ := ret[0].(*Preset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreset indicates an expected call of GetPreset.
func (mr *MockServiceMockRecorder) GetPreset(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreset", reflect.TypeOf((*MockService)(nil).GetPreset), userName)
}

// RequestCancelRun mocks base method.
func (m *MockService) RequestCancelRun(userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestCancelRun", userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestCancelRun indicates an expected call of RequestCancelRun.
func (mr *MockServiceMockRecorder) RequestCancelRun(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestCancelRun", reflect.TypeOf((*MockService)(nil).RequestCancelRun), userName)
}

// RequestSkipNextRun mocks base method.
func (m *MockService) RequestSkipNextRun(userName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestSkipNextRun", userName)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestSkipNextRun indicates an expected call of RequestSkipNextRun.
func (mr *MockServiceMockRecorder) RequestSkipNextRun(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestSkipNextRun", reflect.TypeOf((*MockService)(nil).RequestSkipNextRun), userName)
}

// UpdatePresetRunStatus mocks base method.
func (m *MockService) UpdatePresetRunStatus(userName string, status RunStatus, message string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePresetRunStatus", userName, status, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePresetRunStatus indicates an expected call of UpdatePresetRunStatus.
func (mr *MockServiceMockRecorder) UpdatePresetRunStatus(userName, status, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePresetRunStatus", reflect.TypeOf((*MockService)(nil).UpdatePresetRunStatus), userName, status, message)
}

// UpsertPreset mocks base method.
func (m *MockService) UpsertPreset(p Preset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPreset", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPreset indicates an expected call of UpsertPreset.
func (mr *MockServiceMockRecorder) UpsertPreset(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPreset", reflect.TypeOf((*MockService)(nil).UpsertPreset), p)
}
