// Code generated by MockGen. DO NOT EDIT.
// Source: db.go

// Package db is a generated GoMock package.
package db

import (
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
)

// MockServiceInterface is a mock of ServiceInterface interface.
type MockServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockServiceInterfaceMockRecorder
}

// MockServiceInterfaceMockRecorder is the mock recorder for MockServiceInterface.
type MockServiceInterfaceMockRecorder struct {
	mock *MockServiceInterface
}

// NewMockServiceInterface creates a new mock instance.
func NewMockServiceInterface(ctrl *gomock.Controller) *MockServiceInterface {
	mock := &MockServiceInterface{ctrl: ctrl}
	mock.recorder = &MockServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceInterface) EXPECT() *MockServiceInterfaceMockRecorder {
	return m.recorder
}

// GetAttempts mocks base method.
func (m *MockServiceInterface) GetAttempts(userName string, limit int) ([]Attempt, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAttempts", userName, limit)
	ret0, _ := ret[0].([]Attempt)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAttempts indicates an expected call of GetAttempts.
func (mr *MockServiceInterfaceMockRecorder) GetAttempts(userName, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAttempts", reflect.TypeOf((*MockServiceInterface)(nil).GetAttempts), userName, limit)
}

// GetEnabledPresets mocks base method.
func (m *MockServiceInterface) GetEnabledPresets() ([]Preset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnabledPresets")
	ret0, _ := ret[0].([]Preset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnabledPresets indicates an expected call of GetEnabledPresets.
func (mr *MockServiceInterfaceMockRecorder) GetEnabledPresets() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnabledPresets", reflect.TypeOf((*MockServiceInterface)(nil).GetEnabledPresets))
}

// GetPreset mocks base method.
func (m *MockServiceInterface) GetPreset(userName string) (*Preset, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreset", userName)
	ret0, _ := ret[0].(*Preset)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreset indicates an expected call of GetPreset.
func (mr *MockServiceInterfaceMockRecorder) GetPreset(userName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreset", reflect.TypeOf((*MockServiceInterface)(nil).GetPreset), userName)
}

// LogAttempt mocks base method.
func (m *MockServiceInterface) LogAttempt(a Attempt) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LogAttempt", a)
	ret0, _ := ret[0].(error)
	return ret0
}

// LogAttempt indicates an expected call of LogAttempt.
func (mr *MockServiceInterfaceMockRecorder) LogAttempt(a interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LogAttempt", reflect.TypeOf((*MockServiceInterface)(nil).LogAttempt), a)
}

// PruneAttempts mocks base method.
func (m *MockServiceInterface) PruneAttempts(retention time.Duration) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PruneAttempts", retention)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PruneAttempts indicates an expected call of PruneAttempts.
func (mr *MockServiceInterfaceMockRecorder) PruneAttempts(retention interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PruneAttempts", reflect.TypeOf((*MockServiceInterface)(nil).PruneAttempts), retention)
}

// UpsertPreset mocks base method.
func (m *MockServiceInterface) UpsertPreset(p Preset) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPreset", p)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpsertPreset indicates an expected call of UpsertPreset.
func (mr *MockServiceInterfaceMockRecorder) UpsertPreset(p interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPreset", reflect.TypeOf((*MockServiceInterface)(nil).UpsertPreset), p)
}
